# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('job', models.CharField(choices=[('DeskJob', 'Desk Job'), ('FieldJob', 'Field Job')], max_length=3)),
            ],
        ),
    ]
