# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(choices=[('DeskJob', 'Desk Job'), ('FieldJob', 'Field Job')], max_length=100),
        ),
    ]
