# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-28 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationForm', '0002_auto_20171028_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_time',
            field=models.CharField(choices=[(b'DayJob', b'DayJob'), (b'NightJob', b'NightJob')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(choices=[(b'DeskJob_comp', b'DeskJob_comp'), (b'DeskJob_normal', b'DeskJob_normal')], max_length=100),
        ),
    ]
